<?php
// Generado por tools/build-theme.js a partir del sitio estático. No editar a mano.
if ( ! defined( 'ABSPATH' ) ) exit;

function ugelch_static_pages() {
	return array(
		'actas' => array( 'title' => 'Actas', 'seo' => 'Actas – Ugel Chincheros', 'desc' => 'Actas del Comité de Control Interno de la UGEL Chincheros.', 'nav' => 'actas,diagnostico,planes,implementacion,evaluacion-del-sistema-de-control-interno' ),
		'agenda-institucional' => array( 'title' => 'Agenda Institucional', 'seo' => 'Agenda Institucional – Ugel Chincheros', 'desc' => 'Agenda institucional y calendario de actividades de la UGEL Chincheros.', 'nav' => 'sobre-nosotros,directorio-y-declaracion-jurada,convenios,jurisdiccion,marco-legal,organigrama,agenda-institucional' ),
		'app-interes' => array( 'title' => 'App interes', 'seo' => 'App interes – Ugel Chincheros', 'desc' => 'Aplicaciones de interés para la comunidad educativa: SíseVe, ESCALE, SIMON, SIAGIE, SIGIED y Currículo Nacional.', 'nav' => 'app-interes,consulta-tu-expediente,convocatorias,comunidad-educativa,documentos-de-interes,chincheros-lee' ),
		'auxiliar-de-educacion' => array( 'title' => 'Convocatoria Auxiliar de Educación', 'seo' => 'Convocatoria Auxiliar de Educación – Ugel Chincheros', 'desc' => 'Convocatoria para la contratación de auxiliares de educación en las instituciones educativas de la UGEL Chincheros.', 'nav' => '' ),
		'chincheros-lee' => array( 'title' => 'Chincheros Lee', 'seo' => 'Chincheros Lee – Ugel Chincheros', 'desc' => 'Chincheros Lee: textos de lectura en PDF para los niveles inicial, primaria y secundaria.', 'nav' => 'app-interes,consulta-tu-expediente,convocatorias,comunidad-educativa,documentos-de-interes,chincheros-lee' ),
		'comunidad-educativa' => array( 'title' => 'Comunidad Educativa', 'seo' => 'Comunidad Educativa – Ugel Chincheros', 'desc' => 'Información, enlaces y documentos para administrativos, docentes y directivos de la comunidad educativa de la UGEL Chincheros.', 'nav' => 'app-interes,consulta-tu-expediente,convocatorias,comunidad-educativa,documentos-de-interes,chincheros-lee' ),
		'consulta-tu-expediente' => array( 'title' => 'Consulta tu Expediente', 'seo' => 'Consulta tu Expediente – Ugel Chincheros', 'desc' => 'Gestiones en línea de la UGEL Chincheros: Formulario Único de Trámite (FUT), acceso a la información, pago de derecho y consulta de expedientes.', 'nav' => 'app-interes,consulta-tu-expediente,convocatorias,comunidad-educativa,documentos-de-interes,chincheros-lee' ),
		'convenios' => array( 'title' => 'Convenios', 'seo' => 'Convenios – Ugel Chincheros', 'desc' => 'Convenios institucionales suscritos por la Unidad de Gestión Educativa Local Chincheros.', 'nav' => 'sobre-nosotros,directorio-y-declaracion-jurada,convenios,jurisdiccion,marco-legal,organigrama,agenda-institucional' ),
		'convocatoria-deportivos' => array( 'title' => 'Convocatoria Deportivos', 'seo' => 'Convocatoria Deportivos – Ugel Chincheros', 'desc' => 'Convocatoria para la contratación de técnicos deportivos de los talleres complementarios deportivos y recreativos.', 'nav' => '' ),
		'convocatoria-personal-administrativo' => array( 'title' => 'Convocatoria Personal Administrativo', 'seo' => 'Convocatoria Personal Administrativo – Ugel Chincheros', 'desc' => 'Proceso de contrato de personal administrativo (D. L. 276) de la UGEL Chincheros: comité, cronograma y norma técnica.', 'nav' => '' ),
		'convocatoria-practicante' => array( 'title' => 'Convocatoria Practicante', 'seo' => 'Convocatoria Practicante – Ugel Chincheros', 'desc' => 'Convocatoria de modalidad formativa (practicantes) de la UGEL Chincheros: requisitos y documentos para postular.', 'nav' => '' ),
		'convocatoria-promotores' => array( 'title' => 'Convocatoria Promotores', 'seo' => 'Convocatoria Promotores – Ugel Chincheros', 'desc' => 'Convocatoria para la contratación de promotores culturales de los talleres complementarios EXPRESARTE.', 'nav' => '' ),
		'convocatoria-ugel-chincheros' => array( 'title' => 'Convocatoria Ugel Chincheros', 'seo' => 'Convocatoria Ugel Chincheros – Ugel Chincheros', 'desc' => 'Convocatorias propias de la Unidad de Gestión Educativa Local Chincheros.', 'nav' => '' ),
		'convocatorias' => array( 'title' => 'Convocatorias', 'seo' => 'Convocatorias – Ugel Chincheros', 'desc' => 'Convocatorias de la UGEL Chincheros: auxiliares de educación, CAS, docentes, practicantes, promotores culturales y técnicos deportivos.', 'nav' => '' ),
		'convocatorias-cas' => array( 'title' => 'Convocatorias CAS', 'seo' => 'Convocatorias CAS – Ugel Chincheros', 'desc' => 'Convocatorias CAS de intervenciones educativas de la UGEL Chincheros: requisitos, ficha curricular y declaraciones juradas.', 'nav' => '' ),
		'convocatorias-docentes' => array( 'title' => 'Convocatorias Docentes', 'seo' => 'Convocatorias Docentes – Ugel Chincheros', 'desc' => 'Convocatorias para la contratación de docentes en la jurisdicción de la UGEL Chincheros y normas que las rigen.', 'nav' => '' ),
		'diagnostico' => array( 'title' => 'Diagnóstico', 'seo' => 'Diagnóstico – Ugel Chincheros', 'desc' => 'Diagnóstico del Sistema de Control Interno de la UGEL Chincheros: etapa I, fase de planificación y acciones preliminares.', 'nav' => 'actas,diagnostico,planes,implementacion,evaluacion-del-sistema-de-control-interno' ),
		'direccion' => array( 'title' => 'Direccion', 'seo' => 'Direccion – Ugel Chincheros', 'desc' => 'Dirección de la UGEL Chincheros: máxima autoridad administrativa, responsable de la gestión de la educación básica y técnico productiva.', 'nav' => 'direccion,organo-de-control,organo-de-linea,organos-de-asesoramiento,organos-de-apoyo' ),
		'directorio-y-declaracion-jurada' => array( 'title' => 'Directorio y Declaración Jurada', 'seo' => 'Directorio y Declaración Jurada – Ugel Chincheros', 'desc' => 'Directorio institucional y declaraciones juradas de intereses (DJI) de los funcionarios de la UGEL Chincheros.', 'nav' => 'sobre-nosotros,directorio-y-declaracion-jurada,convenios,jurisdiccion,marco-legal,organigrama,agenda-institucional' ),
		'documentos-de-interes' => array( 'title' => 'Documentos de Interés', 'seo' => 'Documentos de Interés – Ugel Chincheros', 'desc' => 'Documentos de interés de la UGEL Chincheros: comunicados, documentos oficiales y normas emitidas.', 'nav' => 'app-interes,consulta-tu-expediente,convocatorias,comunidad-educativa,documentos-de-interes,chincheros-lee' ),
		'evaluacion-del-sistema-de-control-interno' => array( 'title' => 'Evaluación del Sistema de Control Interno', 'seo' => 'Evaluación del Sistema de Control Interno – Ugel Chincheros', 'desc' => 'Evaluación de la implementación del Sistema de Control Interno de la UGEL Chincheros: reportes y anexos.', 'nav' => 'actas,diagnostico,planes,implementacion,evaluacion-del-sistema-de-control-interno' ),
		'implementacion' => array( 'title' => 'Implementación', 'seo' => 'Implementación – Ugel Chincheros', 'desc' => 'Implementación del Sistema de Control Interno en la UGEL Chincheros.', 'nav' => 'actas,diagnostico,planes,implementacion,evaluacion-del-sistema-de-control-interno' ),
		'jurisdiccion' => array( 'title' => 'Jurisdicción', 'seo' => 'Jurisdicción – Ugel Chincheros', 'desc' => 'Jurisdicción de la UGEL Chincheros: mapa de la provincia de Chincheros, región Apurímac.', 'nav' => 'sobre-nosotros,directorio-y-declaracion-jurada,convenios,jurisdiccion,marco-legal,organigrama,agenda-institucional' ),
		'marco-legal' => array( 'title' => 'Marco Legal', 'seo' => 'Marco Legal – Ugel Chincheros', 'desc' => 'Marco legal de la UGEL Chincheros: Constitución, Ley General de Educación N.° 28044 y demás normas que rigen su gestión.', 'nav' => 'sobre-nosotros,directorio-y-declaracion-jurada,convenios,jurisdiccion,marco-legal,organigrama,agenda-institucional' ),
		'oficios' => array( 'title' => 'Oficios', 'seo' => 'Oficios – Ugel Chincheros', 'desc' => 'Oficios y resoluciones de la UGEL Chincheros para descargar: oficios múltiples, resoluciones viceministeriales y reportes de plazas.', 'nav' => '' ),
		'organigrama' => array( 'title' => 'Organigrama', 'seo' => 'Organigrama – Ugel Chincheros', 'desc' => 'Organigrama de la Unidad de Gestión Educativa Local Chincheros.', 'nav' => 'sobre-nosotros,directorio-y-declaracion-jurada,convenios,jurisdiccion,marco-legal,organigrama,agenda-institucional' ),
		'organo-de-control' => array( 'title' => 'Órgano de Control', 'seo' => 'Órgano de Control – Ugel Chincheros', 'desc' => 'Órgano de Control Institucional (OCI) de la UGEL Chincheros, encargado del control gubernamental según el Sistema Nacional de Control.', 'nav' => 'direccion,organo-de-control,organo-de-linea,organos-de-asesoramiento,organos-de-apoyo' ),
		'organo-de-linea' => array( 'title' => 'Organo de Linea', 'seo' => 'Organo de Linea – Ugel Chincheros', 'desc' => 'Órgano de línea de la Unidad de Gestión Educativa Local Chincheros.', 'nav' => 'direccion,organo-de-control,organo-de-linea,organos-de-asesoramiento,organos-de-apoyo' ),
		'organos-de-apoyo' => array( 'title' => 'Órganos de apoyo', 'seo' => 'Órganos de apoyo – Ugel Chincheros', 'desc' => 'Órganos de apoyo de la UGEL Chincheros: Área de Administración, responsable de abastecimiento, contabilidad y tesorería.', 'nav' => 'direccion,organo-de-control,organo-de-linea,organos-de-asesoramiento,organos-de-apoyo' ),
		'organos-de-asesoramiento' => array( 'title' => 'Órganos de asesoramiento', 'seo' => 'Órganos de asesoramiento – Ugel Chincheros', 'desc' => 'Órganos de asesoramiento de la UGEL Chincheros: Área de Planificación y Presupuesto, a cargo del seguimiento de planes y presupuesto.', 'nav' => 'direccion,organo-de-control,organo-de-linea,organos-de-asesoramiento,organos-de-apoyo' ),
		'planes' => array( 'title' => 'Planes', 'seo' => 'Planes – Ugel Chincheros', 'desc' => 'Planes del Sistema de Control Interno de la UGEL Chincheros: etapa II, identificación de brechas y oportunidades de mejora.', 'nav' => 'actas,diagnostico,planes,implementacion,evaluacion-del-sistema-de-control-interno' ),
		'preguntas-frecuentes' => array( 'title' => 'Preguntas frecuentes', 'seo' => 'Preguntas frecuentes – Ugel Chincheros', 'desc' => 'Preguntas frecuentes sobre los trámites y servicios de la UGEL Chincheros.', 'nav' => 'tupa,preguntas-frecuentes' ),
		'sobre-nosotros' => array( 'title' => 'Sobre Nosotros', 'seo' => 'Sobre Nosotros – Ugel Chincheros', 'desc' => 'Quiénes somos: la UGEL Chincheros es una instancia descentralizada del Gobierno Regional de Apurímac. Conoce su misión y visión.', 'nav' => 'sobre-nosotros,directorio-y-declaracion-jurada,convenios,jurisdiccion,marco-legal,organigrama,agenda-institucional' ),
		'tupa' => array( 'title' => 'TUPA', 'seo' => 'TUPA – Ugel Chincheros', 'desc' => 'Texto Único de Procedimientos Administrativos (TUPA) de la UGEL Chincheros: requisitos y procedimientos de los trámites.', 'nav' => 'tupa,preguntas-frecuentes' ),
	);
}

// Menús laterales de sección: clave = lista de slugs, valor = [slug, etiqueta]
function ugelch_side_navs() {
	return array(
		'actas,diagnostico,planes,implementacion,evaluacion-del-sistema-de-control-interno' => array( array( 'actas', 'Actas' ), array( 'diagnostico', 'Diagnóstico' ), array( 'planes', 'Planes' ), array( 'implementacion', 'Implementación' ), array( 'evaluacion-del-sistema-de-control-interno', 'Evaluación del Sistema de Control Interno' ) ),
		'sobre-nosotros,directorio-y-declaracion-jurada,convenios,jurisdiccion,marco-legal,organigrama,agenda-institucional' => array( array( 'sobre-nosotros', 'Sobre Nosotros' ), array( 'directorio-y-declaracion-jurada', 'Directorio y Declaración Jurada' ), array( 'convenios', 'Convenios' ), array( 'jurisdiccion', 'Jurisdicción' ), array( 'marco-legal', 'Marco Legal' ), array( 'organigrama', 'Organigrama' ), array( 'agenda-institucional', 'Agenda Institucional' ) ),
		'app-interes,consulta-tu-expediente,convocatorias,comunidad-educativa,documentos-de-interes,chincheros-lee' => array( array( 'app-interes', 'App interes' ), array( 'consulta-tu-expediente', 'Consulta tu Expediente' ), array( 'convocatorias', 'Convocatorias' ), array( 'comunidad-educativa', 'Comunidad Educativa' ), array( 'documentos-de-interes', 'Documentos de Interés' ), array( 'chincheros-lee', 'Chincheros Lee' ) ),
		'direccion,organo-de-control,organo-de-linea,organos-de-asesoramiento,organos-de-apoyo' => array( array( 'direccion', 'Direccion' ), array( 'organo-de-control', 'Órgano de Control' ), array( 'organo-de-linea', 'Organo de Linea' ), array( 'organos-de-asesoramiento', 'Órganos de asesoramiento' ), array( 'organos-de-apoyo', 'Órganos de apoyo' ) ),
		'tupa,preguntas-frecuentes' => array( array( 'tupa', 'TUPA' ), array( 'preguntas-frecuentes', 'Preguntas frecuentes' ) ),
	);
}
